FROM python:3.10-slim

WORKDIR /app

COPY ./src ./src
COPY ./requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

ENV PYHONPATH="/app/src"

EXPOSE 8000

CMD ["python", "src/main.py"]