HOST = "0.0.0.0"
PORT = 8003

HOST_DB = "mariadb"
PORT_DB = 3306
USER_DB = "user_db"
USER_PASSWORD_DB = "userpw"
DATABASE_NAME_DB = "turing_db"

OLLAMA_CHAT_URL = "http://ollama:11434/api/chat"
MODEL = "gemma3:1b"

NUM_QUESTIONS_PER_GAME = 3

JUDGE_WON_POINTS = 3
JUDGE_LOST_POINTS = -2

PART_WON_POINTS = 1
PART_LOST_POINTS = 0